buildscript {
    ext.kotlin_version = "1.9.0"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.0'
        classpath "com.google.gms:google-services:4.4.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// Load GitHub credentials from credentials.properties
def credentialsFile = rootProject.file("credentials.properties")
def credentialsProps = new Properties()

if (credentialsFile.exists()) {
    credentialsFile.withInputStream {
        credentialsProps.load(it)
    }
} else {
    throw new RuntimeException("Missing credentials.properties file!")
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url credentialsProps['FINVUURL']
            credentials {
                username = credentialsProps['USERNAME']
                password = credentialsProps['PASSWORD']
            }
        }
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
