allprojects {
    repositories {
        google()
        mavenCentral()
        maven { 
            url 'https://maven.pkg.github.com/yashwantGehlot/finvu_android_sdk' 
            credentials {
                username = "NILESHTOSHNIWAL536"
                password = "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"
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
