// buildscript {
//     repositories {
//         google()   // Add Google repository
//         mavenCentral() // Ensure Maven Central is present
//     }
//     dependencies {
//         classpath 'com.android.tools.build:gradle:8.2.2'
//         classpath "com.google.gms:google-services:4.4.2"
//     }
// }

// allprojects {
//     repositories {12
//         google()
//         mavenCentral()
//         maven { 
//             url 'https://maven.pkg.github.com/Cookiejar-technologies/finvu_android_sdk' 
//             credentials {
//                 username = "NILESHTOSHNIWAL536"
//                 password = "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"
//             }
//         }
//     }
// }

// rootProject.buildDir = "../build"
// subprojects {
//     project.buildDir = "${rootProject.buildDir}/${project.name}"
// }

// subprojects {
//     project.evaluationDependsOn(":app")
// }

// tasks.register("clean", Delete) {
//     delete rootProject.buildDir
// }

buildscript {
    ext.kotlin_version = "1.9.0"
    repositories {
        google()   // Add Google repository
        mavenCentral() // Ensure Maven Central is present
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "com.google.gms:google-services:4.4.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { 
            url 'https://maven.pkg.github.com/Cookiejar-technologies/finvu_android_sdk' 
            credentials {
                username = "NILESHTOSHNIWAL536"
                password = "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"
            }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}