# org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:-UseCompressedOops -XX:HeapBaseMinAddress=32G
# android.useAndroidX=true
# android.enableJetifier=true
# # org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.7.7-hotspot
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
# android.injected.apk.alignPageSize=16384




# Gradle JVM memory & encoding
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# AndroidX support
android.useAndroidX=true
android.enableJetifier=true

# Java JDK path
org.gradle.java.home=C:\\Users\\NH2323\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-17.0.14.7-hotspot

# Stability tweaks
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false

# Optional APK alignment
android.injected.apk.alignPageSize=16384
