// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLlFwWzO_WJS_fb4cGBglhR2iizF-6zY',
    appId: '1:437443695891:android:3137c41f516db70df7f6e6',
    messagingSenderId: '437443695891',
    projectId: 'stakeplot-9f34b',
    storageBucket: 'stakeplot-9f34b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsLQjLKVD8LJ7-cwanwi81ji0nIaHX8Wg',
    appId: '1:437443695891:ios:2847cc592d577612f7f6e6',
    messagingSenderId: '437443695891',
    projectId: 'stakeplot-9f34b',
    storageBucket: 'stakeplot-9f34b.firebasestorage.app',
    androidClientId: '437443695891-25ip6du0dnr12u3lhvu8lqmheoqd4ls5.apps.googleusercontent.com',
    iosClientId: '437443695891-m14tpii5cje8ql2up3avtso1d1dhf108.apps.googleusercontent.com',
    iosBundleId: 'com.stakeplot.pfa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJCPCXlWdtucIGGxgEvpGQq4tBWtrVUpU',
    appId: '1:437443695891:web:aa9cc4d4652ef6bdf7f6e6',
    messagingSenderId: '437443695891',
    projectId: 'stakeplot-9f34b',
    authDomain: 'stakeplot-9f34b.firebaseapp.com',
    storageBucket: 'stakeplot-9f34b.firebasestorage.app',
    measurementId: 'G-0T97YEWBGB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsLQjLKVD8LJ7-cwanwi81ji0nIaHX8Wg',
    appId: '1:437443695891:ios:cdb6e3a2d41a2173f7f6e6',
    messagingSenderId: '437443695891',
    projectId: 'stakeplot-9f34b',
    storageBucket: 'stakeplot-9f34b.firebasestorage.app',
    androidClientId: '437443695891-nqfnov7duvd3j5olorsuab5kv7mbuqgb.apps.googleusercontent.com',
    iosClientId: '437443695891-u0prp24l7ktkkhn9jhgh886263i3sq56.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationCodeStakeplot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJCPCXlWdtucIGGxgEvpGQq4tBWtrVUpU',
    appId: '1:437443695891:web:cb4d080959e3fd67f7f6e6',
    messagingSenderId: '437443695891',
    projectId: 'stakeplot-9f34b',
    authDomain: 'stakeplot-9f34b.firebaseapp.com',
    storageBucket: 'stakeplot-9f34b.firebasestorage.app',
    measurementId: 'G-F1L2L7FYG8',
  );

}