const categories = {
  Food: [
    'Swiggy',
    'Zomato',
    'Restaurant',
    'Cafe',
    'Pizza',
    'Dairy',
    'Tea',
    'Chai',
    'canteen',
    'Bistro',
    'Mcdonalds',
    'kfc',
    'subway',
    'dominos',
    'Dhaba',
    'Chicken',
    'Italia',
    'bawarchi',
    'cafe',
    'Tiffin',
    'meals',
    'udupi',
    'coffee',
    'eats',
    'Frankie',
    'kirana',
    'Store',
    'General Store',
    'rasoi',
    'fish',
    'milk',
    'Burger King',
    'Foods',
    'juice',
    'Ration',
    'Mithai',
    'Biryani',
    'Pizza',
    'Burger',
    'Chinese',
    'Sweet Shop',
    'Street Food',
    'Fast Food',
    'Canteen',
    'Mess',
    'Tea Stall',
    'Coffee Shop',
    'hotel',
    'cater',
    'restau',
    'catering',
    'Taco Bell',
    'BAKERS',
    'FOODS',
    'PISTA HOUSE',
    'Shah Gouse',
    'mutton',
    'mehfil',
    'tiffins',
  ],
  Shopping: [
    'Shoppers',
    'Mart',
    'WestSide',
    'Electronics',
    'Supermarket',
    'Amazon',
    'Flipkart',
    'Fashion',
    'Fabrics',
    'kart',
    'Aditya Birla',
    'shopping',
    'Mobiles',
    'lifestyle',
    'market',
    'more',
    'shop',
    'max',
    'zudio',
    'centro',
    'Purchase',
    'Buy',
    'Shop',
    'Retail',
    'Bazaar',
    'Merchant',
    'Store',
    'Centre',
    'Mall',
    'Textiles',
    'Garments',
    'Furniture',
    'Hardware',
    'Footwear',
    'Jewellery',
    'Stationery',
    'Bookstore',
    'Salon',
    'Spa',
    'Laundry',
    'Tailor',
    'trading',
    'Trends',
    'rareandbasics',
  ],
  Groceries: [
    'SUPRDAILY',
    'GROCERY',
    "SPENCER'S",
    'METRO CASH',
    'VEGETABLE',
    'FRUIT',
    'Ratnadeep',
    'dmart',
    'Veggie',
    'kirana',
    'General Store',
    'milk',
    'innovdmartts',
    'ZEPTO',
  ],
  Travel: [
    'Fuel',
    'Petrol',
    'Ola',
    'Uber',
    'Metro',
    'Traffic police',
    'puncture',
    'Mobility',
    'OlaCabs',
    'Travels',
    'Transport',
    'Filling',
    'Parking',
    'Rapido',
    'Tgsrtc',
    'irctc',
    'Apsrtc',
    'Toll',
    'CNG',
    'Diesel',
    'Blusmart',
    'railways',
    'railway',
    'airport',
    'TRAVEL',
    'TSRTC',
    'HYDMETROINAPP',
    'PETROLEUM',
    'REDBUS',
  ],
  Health: [
    'Medical',
    'Pharmacy',
    'Hospital',
    'Medplus',
    'Clinic',
    'Doctor',
    'Medicine',
    'Treatment',
    'Diagnostic',
    'Lab',
    'Test',
    'Scan',
    'Surgery',
    'Therapy',
    'Dental',
    'Ayurveda',
    'Homeopathy',
    'Wellness',
  ],
  Bills: [
    'Electricity',
    'Water',
    'Gas',
    'Internet',
    'Mobile Recharge',
    'Rent',
    'Housing',
    'PG',
    'Hostel',
    'Flat',
    'Apartment',
    'Landlord',
    'DTH',
    'AIRTEL',
    'JIO',
    'Solutions',
    'godaddy',
    'hostinger',
    'bpcl',
    'IDEA',
    'VI',
    'BSNL',
    'ACT',
    'HATHWAY',
    'TATA',
    'charges',
    'chrg',
    'playstore',
  ],
  Subscriptions: [
    'Netflix',
    'PrimeVideo',
    'Spotify',
    'Jio Hotstar',
    'appleServices',
    'disney',
    'Googleplay',
    'Swiggy',
    'Zomato',
    'HOTSTAR+',
    'ZEE5',
    'MUX PLAY',
    'BLINKIT+',
    'SONYLIV',
    'JIO CINEMA',
    'VOOT',
    'ALT BALAJI',
    'EPIC ON',
    'GAANA',
  ],
  Events: ['Weddings', 'Birthday', 'Festival', 'Anniversary', 'Flowers', 'pubs', 'Gift'],
  'Personal Care': ['Salon', 'Spa', 'Haircare', 'Skincare'],
  Services: [
    'Housemaid',
    'Carpenter',
    'Electrician',
    'Plumber',
    'Bike Service',
    'Car Service',
    'Hardware',
    'Sanitary',
    'Events',
    'Service',
    'Bike',
    'hardware',
    'sanitary',
    'communications',
    'traders',
    'Enterprises',
    'solutions',
  ],
  Emi: ['Eazypay', 'slice', 'postpaid', 'loan', 'mpocket', 'emi', 'finance', 'mpokket'],
  Investments: [
    'MutualFund',
    'Stocks',
    'Gold',
    'Jar',
    'Investment',
    'Fund',
    'Portfolio',
    'Dividend',
    'Fixed Deposit',
    'FD',
    'Recurring Deposit',
    'RD',
    'PPF',
    'SIP',
    'Equity',
    'Stocks',
    'Bonds',
    'Gold',
    'NPS',
    'Pension',
    'Brokerage',
    'Trading',
    'payout',
    'sweepout',
    'td',
    'MutualFunds',
  ],
  Insurance: ['Life Insurance', 'Vehicle Insurance', 'POLICYBAZAAR'],
  Income: [
    'NEFT',
    'NEFT CR',
    'PRINC PAYOUT',
    'INT PAYOUT',
    'Salary',
    'credit interest',
    'BIL',
    'INF',
    'zerodhabroking',
    'credit',
    'refund',
  ],
  Support: ['Charity', 'Trust', 'ngo', 'Donation', 'Help charity'],
  Current: ['TDS'],
  Children: [
    'School Fees',
    'Tuitions',
    'Baby store',
    'miniklub',
    'uniforms',
    'baby care',
    'children',
    'firstcry',
    'TOY STORE',
    'hamleys',
  ],
  'Pet Care': ['Pet'],
  Sports: [
    'Gym Membership',
    'Sports Equipment',
    'Snooker',
    'cricket',
    'box',
    'DECATHLON',
    'SPORTS360',
    'FITPASS',
    'CRICKET STORE',
    'GYMCRM',
    'YOGA STUDIO',
  ],
  Alcohol: ['Liquor', 'Wine', 'Pub', 'whiskey'],
  Hobbies: ['Photography', 'Gardening'],
  Education: [
    'Stationary',
    'Fees',
    'Fee',
    'institute',
    'college',
    'School',
    'University',
    'Institute',
    'Tuition',
    'Coaching',
    'Academy',
    'Admission',
    'Examination',
    'Books',
    'Uniform',
    'Hostel',
    'Seminar',
    'Workshop',
  ],
  Commerce: [
    'Amazon',
    'Flipkart',
    'Myntra',
    'Nykaa',
    'Bluedart',
    'ekart',
    'Delhivery',
    'e cart',
    'netmeds',
    '1mg',
    'BIGBASKET',
    'GROFERS',
    'INSTAMART',
    'blinkit',
  ],
  snacks: [
    'juice',
    'Sweets',
    'Chai',
    'Biscuit',
    'Thickshake',
    'chocolate',
    'Ice cream',
    'chat',
    'mithai',
    'Bakes',
    'Bakery',
    'Cakes',
    'Tea',
    'chips',
    'confectioners',
    'cool drink',
    'CHAAT',
  ],
  Entertainment: [
    'Bookmyshow',
    'district',
    'gokarting',
    'gaming',
    'Entertainment',
    'pvr',
    'cinepolis',
    'imax',
    'Escape',
    'Adventures',
  ],
  'Personal Transfer': ['POS', 'CASH WDL', 'ATM', 'To:'],
  'Personal Transfer Received': ['UPI-CR', 'UPI CR'],
  'Bank Charges': [
    'NEFT CHARGE',
    'IMPS CHARGE',
    'ATM FEE',
    'SERVICE CHARGE',
    'ANNUAL FEE',
    'CHEQUE BOOK CHARGE',
    'SMS ALERT CHARGE',
  ],
};

export default categories;
