import 'package:finvu_flutter_sdk_core/finvu_linked_accounts.dart';
import 'package:flutter/material.dart';
import 'package:flutter_application_code_stakeplot/Constants/font_manager.dart';
import 'package:flutter_application_code_stakeplot/Home_Screen/colors.dart';
import 'package:flutter_application_code_stakeplot/Utils/snackBar.dart';
import 'package:flutter_application_code_stakeplot/controllers/post-controller.dart';
import 'package:flutter_application_code_stakeplot/controllers/user-controller.dart';
import 'package:flutter_application_code_stakeplot/finance_screen/Debts/CreateDebtScreen.dart';
import 'package:flutter_application_code_stakeplot/model/TransactionModel.dart';
import 'package:get/get.dart';
import 'package:top_snackbar_flutter/custom_snack_bar.dart';
import 'package:top_snackbar_flutter/top_snack_bar.dart';
part 'snackBars.dart';

bool flag = true;
String portNo = flag ? "192.168.1.10" : "localhost";
String urlWithLocallHost =flag ? "https://stakeplot.in/" : "http://${portNo}:5000/";
String url = "${urlWithLocallHost}api/v1";
String valid = "Please Enter All Fields";
UserController get userController => Get.find<UserController>();
PostController get postController => Get.find<PostController>();
RxMap deviceData = {}.obs;
RxBool isBankAccountLink = false.obs;
RxInt scrollBankPage = 0.obs;
double maxDC = 0;
double minDC = 0;
RxList notificationList = [].obs;
RxList<String> listofLinkedAccount = <String>[].obs;
RxList trasactionsData = [].obs;
RxList listOfRecentTrasactionsData = [].obs;
RxList trasactionsHideData = [].obs;
RxList trasactionsHistory = [].obs;
RxBool getHistory = false.obs;
RxList lendAmountRemainders = [].obs;
RxBool getlendUsers = false.obs;
List<double> trasactionsDataMonthlyCredit = [];
List<double> trasactionsDataMonthlyDebit = [];
List<double> trasactionsDataCustomCredit = [];
List<double> trasactionsDataCustomDebit = [];
List<String> trasactionsDataCustomLabel = [];
RxBool flagTrasaction = false.obs;
RxBool isFromEditDeatils = false.obs;
RxString range = ''.obs;
RxString filterText = ''.obs;
RxString defaultBackGround = "#68B2A0".obs;
List<double> trasactionsDataCreditWeekly = [];
List<double> trasactionsDataDebitWeekly = [];
RxList trasactionsDataWeekly = [].obs;
RxList friendRequestList = [].obs;
RxList messages = [].obs;
RxList messagesTemp = [].obs;
RxList roomBills = [].obs;
RxList questionRoom = [].obs;
RxList productList = [].obs;
RxList userPostList = [].obs;
RxList chatList = [].obs;
RxList chatListOriginal = [].obs;
RxList chatListMasked = [].obs;
RxList chatListOriginalMasked = [].obs;
RxList customCategoryList = [].obs;
RxMap friendsListDetails = {}.obs;
RxMap chatOfUserList = {}.obs;
RxMap chatOfUserListData = {}.obs;
List<Map<String, dynamic>> custom = [];
RxBool hideTransactionReload = false.obs;
RxBool aboutMe = false.obs;
RxBool myNotificationBool = false.obs;
RxBool clickedLinkedBackAccount = false.obs;
RxBool setBankAccountPassword = false.obs;
RxBool hideBackAccountPassword = false.obs;
bool sizeRoom = false;
double fontSize = 20;
RxInt budgetLength = 0.obs;
RxInt billLength = 0.obs;
RxInt debtLength = 0.obs;
RxInt paymentLength = 0.obs;
RxString splitID = "".obs;
RxString openTrasactions = "Bills".obs;
RxString targetString = "".obs;
RxList categoriesList = [].obs;
RxList moreDrasticChange = [].obs;
RxList frequentPayments = [].obs;
RxDouble totalDebitThisMonth = 0.0.obs;
RxDouble totalDebitThisWeek = 0.0.obs;
RxList categoriesListWeek = [].obs;
RxList moreDrasticChangeWeek = [].obs;
RxList frequentPaymentsWeek = [].obs;
Map<String, dynamic> loginUsersList = Map<String, dynamic>();
RxList dueAmountRemainders = [].obs;
RxBool getdueUsers = false.obs;
RxBool canMessageUser = false.obs;
RxInt selectedYear = DateTime.now().year.obs;
RxInt selectedMonth = DateTime.now().month.obs;
RxList inSights = [].obs;
RxBool getInsights = false.obs;
RxBool allOrGroupTransactions = true.obs;
RxString accountId = "".obs;
RxString searchAccountId = "".obs;
RxString accountIdPdf = "".obs;
RxString accountSelected = "".obs;
RxString maskedNameLocal = "".obs;
RxString allOrGroupTransactionsName = "All".obs;
RxList totalInSights = [].obs;
RxBool getTotalInsightsHistory = false.obs;
RxList foodieFundsDetailsRemainders = [].obs;
RxBool getFoodieFundsUsers = false.obs;
RxBool isGoogleUser = false.obs;
late BuildContext contextGlobal;
bool limitTagbool = false;
int currentPage = 1;
RxBool havingMoreData = true.obs;
RxBool isLoadingMore = false.obs;
RxBool loadMoreData = false.obs;
bool hasMoreData = true;
int m = DateTime.now().month;
List targetsData = [];
List arr = [];
List scrollAbleList = [].obs;
List scrollAbleListALl = [].obs;
RxBool bol = false.obs;
String tabAmount = "";
RxInt listIndex = 0.obs;
RxBool reRender = false.obs;
RxBool reGraph = false.obs;
RxBool setDonectChat = false.obs;
List room = [];
List<String> account = [];
RxBool acceptReset = false.obs;
RxBool LoadTag = false.obs;
RxList budgetList = [].obs;
final RxList<Debt> debts = <Debt>[].obs;
RxList debtsList = [].obs;
RxList historyListData = [].obs;
RxBool hasGetNewNotifications = false.obs;
RxBool getGraphData = false.obs;
RxBool loadBanks = true.obs;
RxBool loadBalance = true.obs;
RxBool isSplit = false.obs;
RxBool isLend = false.obs;
RxBool stopTonavigate = true.obs;
final GlobalKey targetKey = GlobalKey();
RxString selectedButton2 = 'Month'.obs;
RxString selectedButton = 'Month'.obs; // Default view is "Month"
DateTimeRange? selectedDateRange; // Default view is "Month"
int selectedDay = 1;
int year = DateTime.now().year; // Current year
Map<int, List<double>> creditedData = {};
Map<int, List<double>> debitedData = {};
double totalSpent = 0.0;
RxMap<String, List<double>> transactionChatGraph = new RxMap();
RxBool graphTransaction = false.obs;
List<String> labels = [];
List<String> labels2 = [];
RxDouble maxYValue = 0.0.obs;
RxList<TransactionModel> hiddentrasactionsHistory = <TransactionModel>[].obs;
RxList<TransactionModel> transactionsHistory = <TransactionModel>[].obs;
RxBool getHiddenHistory = false.obs;
RxBool isYearView = false.obs;
RxBool loadChatdataOnChnage = false.obs;
RxBool loadingDelay = false.obs;
RxDouble totalDebitValue = 0.0.obs;
RxDouble totalExpandedValue = 0.0.obs;
List<double> trasactionsDataDebitWeeklyoverall = [];
RxMap<String, List<double>> transactionChatGraphoverall = new RxMap();
RxDouble maxYValueoverall = 0.0.obs;
RxBool getGraphDataoverall = false.obs;
RxDouble totalDebitValuePercent = 0.0.obs;

final RxList<String> monthLabels = <String>[].obs;
final Rx<Map<String, List<double>>> currentChartData =
    Rx<Map<String, List<double>>>({});
final RxList<String> currentDays = <String>[].obs;
final RxBool isLoading = false.obs;
late FinvuAccountLinkingRequestReference linkingReference;

RxString nextFecthDate = "".obs;
RxString LastFetchDate = "".obs;
RxString fetchCount = "".obs;
RxString BankName = "".obs;
RxString BankUrl = "".obs;
RxString transactionsId = "".obs;

RxBool isFected = false.obs;
RxInt transactionsLength = 0.obs;
RxList chatSplitAccount = [].obs;
RxBool getChatSplit = false.obs;

DateTime startDateCustom = DateTime.now().subtract(const Duration(days: 7));
DateTime endDateCustom = DateTime.now();
