name: QA CI/CD

on:
  push:
    branches:
      - dev_roshan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: 058264382454.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: bank-service
        run: |
          docker build --platform linux/amd64 -t $ECR_REPOSITORY:staging .
          docker tag $ECR_REPOSITORY:staging $ECR_REGISTRY/$ECR_REPOSITORY:staging
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:staging

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/devops-tools/scripts
            ./docker-control.base.sh qa down bank-service
            docker rm -f bank-service || true
            docker pull 058264382454.dkr.ecr.ap-south-1.amazonaws.com/bank-service:staging
            ./docker-control.base.sh qa up bank-service
